// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var baseLayer, icon, map;
    map = new L.Map('map', {
      maxZoom: 19,
      scrollWheelZoom: false,
      zoomControl: false
    });
    baseLayer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 18
    });
    map.addLayer(baseLayer);
    map.setView(new L.LatLng(41.866333, -87.606783), 15);
    icon = L.icon({
      iconSize: new L.Point(25, 41),
      iconAnchor: new L.Point(12, 41),
      popupAnchor: new L.Point(1, -34),
      shadowSize: new L.Point(41, 41),
      iconUrl: 'images/marker-icon.png',
      iconRetinaUrl: 'images/marker-icon@2x.png',
      shadowUrl: 'images/marker-shadow.png'
    });
    L.marker([41.866333, -87.606783], {
      icon: icon
    }).addTo(map);
    $("#backgrounds div").each(function() {
      var startingPosY;
      startingPosY = parseInt($(this).css("background-position").split(" ")[1]);
      return $(this).attr("data-startingPosY", startingPosY);
    });
    $(window).scroll(function() {
      return $("#backgrounds div").each(function() {
        var bpos, posY, scroll, speed;
        speed = $(this).data().speed;
        posY = $(this).data().startingposy;
        scroll = $(window).scrollTop() * speed;
        bpos = $(this).css('background-position');
        bpos = bpos.split(" ")[0] + (" " + (posY - scroll) + "px");
        return $(this).css('background-position', bpos);
      });
    });
    Galleria.loadTheme('lib/themes/classic/galleria.classic.min.js');
    return Galleria.run('#galleria');
  });

}).call(this);
